/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HIazXnrmem5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function badge() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="sticky top-0 z-50 w-full border-b border-border bg-background/90 backdrop-blur-sm">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CodeIcon className="h-6 w-6" />
            <span className="font-bold">John Doe</span>
          </Link>
          <nav className="hidden items-center gap-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Skills
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="ghost" size="icon" className="md:hidden" aria-label="Toggle navigation menu">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section id="about" className="container flex flex-col items-center justify-center gap-8 py-12 md:py-24">
          <div className="grid gap-4 text-center">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Hi, I'm John Doe</h1>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              I'm a software engineering intern with a passion for building innovative and user-friendly applications.
              I'm excited to contribute my skills and expertise to your team.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <CodeIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Coding</h3>
              <p className="text-muted-foreground">Proficient in JavaScript, React, and Node.js.</p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <PuzzleIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Problem-Solving</h3>
              <p className="text-muted-foreground">
                Skilled at breaking down complex problems and finding efficient solutions.
              </p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <LayersIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Design</h3>
              <p className="text-muted-foreground">
                Experienced in creating user-friendly interfaces and responsive designs.
              </p>
            </Card>
          </div>
        </section>
        <section id="skills" className="container flex flex-col items-center justify-center gap-8 py-12 md:py-24">
          <div className="grid gap-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Skills</h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              I have a diverse set of skills that I've developed through my education and internship experiences.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <CodepenIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">React</h3>
              <p className="text-muted-foreground">
                Experienced in building responsive and scalable web applications using React.
              </p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <NetworkIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Node.js</h3>
              <p className="text-muted-foreground">
                Proficient in building server-side applications and APIs using Node.js and Express.
              </p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <DatabaseIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Databases</h3>
              <p className="text-muted-foreground">
                Experienced in working with SQL and NoSQL databases, including PostgreSQL and MongoDB.
              </p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <GitGraphIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Git</h3>
              <p className="text-muted-foreground">Proficient in using Git for version control and collaboration.</p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <CodepenIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">CSS</h3>
              <p className="text-muted-foreground">
                Experienced in creating responsive and visually appealing designs using CSS.
              </p>
            </Card>
            <Card className="flex flex-col items-center justify-center gap-2 p-6 transition-all hover:bg-muted">
              <TestTubeIcon className="h-8 w-8" />
              <h3 className="text-lg font-semibold">Testing</h3>
              <p className="text-muted-foreground">
                Proficient in writing unit and integration tests using frameworks like Jest and Enzyme.
              </p>
            </Card>
          </div>
        </section>
        <section id="projects" className="container flex flex-col items-center justify-center gap-8 py-12 md:py-24">
          <div className="grid gap-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">My Projects</h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              Here are some of the projects I've worked on during my software engineering internship.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
            <Card className="flex flex-col gap-4 p-6 transition-all hover:bg-muted">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Project 1"
                className="rounded-md object-cover"
              />
              <div className="grid gap-2">
                <h3 className="text-lg font-semibold">Project 1</h3>
                <p className="text-muted-foreground">
                  A web application that helps users manage their daily tasks and to-do lists.
                </p>
                <div className="flex gap-2">
                  <Badge>React</Badge>
                  <Badge>Node.js</Badge>
                  <Badge>MongoDB</Badge>
                </div>
                <div className="flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    prefetch={false}
                  >
                    View Project
                    <ArrowRightIcon className="h-4 w-4" />
                  </Link>
                </div>
              </div>
            </Card>
            <Card className="flex flex-col gap-4 p-6 transition-all hover:bg-muted">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Project 2"
                className="rounded-md object-cover"
              />
              <div className="grid gap-2">
                <h3 className="text-lg font-semibold">Project 2</h3>
                <p className="text-muted-foreground">
                  A mobile-friendly e-commerce website that allows users to browse and purchase products.
                </p>
                <div className="flex gap-2">
                  <Badge>React</Badge>
                  <Badge>Node.js</Badge>
                  <Badge>PostgreSQL</Badge>
                </div>
                <div className="flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    prefetch={false}
                  >
                    View Project
                    <ArrowRightIcon className="h-4 w-4" />
                  </Link>
                </div>
              </div>
            </Card>
            <Card className="flex flex-col gap-4 p-6 transition-all hover:bg-muted">
              <img
                src="/placeholder.svg"
                width={600}
                height={400}
                alt="Project 3"
                className="rounded-md object-cover"
              />
              <div className="grid gap-2">
                <h3 className="text-lg font-semibold">Project 3</h3>
                <p className="text-muted-foreground">
                  A web application that allows users to track their fitness goals and progress.
                </p>
                <div className="flex gap-2">
                  <Badge>React</Badge>
                  <Badge>Node.js</Badge>
                  <Badge>MongoDB</Badge>
                </div>
                <div className="flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                    prefetch={false}
                  >
                    View Project
                    <ArrowRightIcon className="h-4 w-4" />
                  </Link>
                </div>
              </div>
            </Card>
          </div>
        </section>
        <section id="contact" className="container flex flex-col items-center justify-center gap-8 py-12 md:py-24">
          <div className="grid gap-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get in Touch</h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl">
              I'd love to hear from you! Feel free to reach out with any questions or opportunities.
            </p>
          </div>
          <Card className="w-full max-w-md">
            <CardContent className="grid gap-4">
              <form className="grid gap-4">
                <Input type="text" placeholder="Name" className="w-full" required />
                <Input type="email" placeholder="Email" className="w-full" required />
                <Textarea placeholder="Message" rows={4} className="w-full" required />
                <Button type="submit" className="justify-self-end">
                  Send Message
                </Button>
              </form>
            </CardContent>
          </Card>
        </section>
      </main>
      <footer className="bg-muted py-6 text-center text-muted-foreground">
        <div className="container">
          <p>&copy; 2024 John Doe. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function GitGraphIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z" />
      <path d="m22 17.65-9.17 4.16a2 2 0 0 1-1.66 0L2 17.65" />
      <path d="m22 12.65-9.17 4.16a2 2 0 0 1-1.66 0L2 12.65" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function PuzzleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19.439 7.85c-.049.322.059.648.289.878l1.568 1.568c.47.47.706 1.087.706 1.704s-.235 1.233-.706 1.704l-1.611 1.611a.98.98 0 0 1-.837.276c-.47-.07-.802-.48-.968-.925a2.501 2.501 0 1 0-3.214 3.214c.446.166.855.497.925.968a.979.979 0 0 1-.276.837l-1.61 1.61a2.404 2.404 0 0 1-1.705.707 2.402 2.402 0 0 1-1.704-.706l-1.568-1.568a1.026 1.026 0 0 0-.877-.29c-.493.074-.84.504-1.02.968a2.5 2.5 0 1 1-3.237-3.237c.464-.18.894-.527.967-1.02a1.026 1.026 0 0 0-.289-.877l-1.568-1.568A2.402 2.402 0 0 1 1.998 12c0-.617.236-1.234.706-1.704L4.23 8.77c.24-.24.581-.353.917-.303.515.077.877.528 1.073 1.01a2.5 2.5 0 1 0 3.259-3.259c-.482-.196-.933-.558-1.01-1.073-.05-.336.062-.676.303-.917l1.525-1.525A2.402 2.402 0 0 1 12 1.998c.617 0 1.234.236 1.704.706l1.568 1.568c.23.23.556.338.877.29.493-.074.84-.504 1.02-.968a2.5 2.5 0 1 1 3.237 3.237c-.464.18-.894.527-.967 1.02Z" />
    </svg>
  )
}


function TestTubeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2v17.5c0 1.4-1.1 2.5-2.5 2.5h0c-1.4 0-2.5-1.1-2.5-2.5V2" />
      <path d="M8.5 2h7" />
      <path d="M14.5 16h-5" />
    </svg>
  )
}
