/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SF0QfvTPH33
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Rubik } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function portfolio() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto flex h-16 max-w-6xl items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
            <CodeIcon className="h-6 w-6" />
            <span>Jane Doe</span>
          </Link>
          <nav className="hidden space-x-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Skills
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button variant="ghost" size="icon" className="rounded-full md:hidden" aria-label="Toggle navigation menu">
            <MenuIcon className="h-6 w-6" />
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section id="hero" className="container mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32">
          <div className="grid gap-8 md:grid-cols-2 md:items-center">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Hi, I'm Jane Doe</h1>
              <p className="text-muted-foreground">
                I'm a software engineering intern with a passion for building innovative and user-friendly web
                applications.
              </p>
              <div className="flex gap-4">
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  View Resume
                </Link>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                  prefetch={false}
                >
                  Contact Me
                </Link>
              </div>
            </div>
            <div className="flex justify-center">
              <img src="/placeholder.svg" width={400} height={400} alt="Jane Doe" className="rounded-full" />
            </div>
          </div>
        </section>
        <section id="about" className="container mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32">
          <div className="grid gap-8 md:grid-cols-2">
            <div>
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">About Me</h2>
              <p className="mt-4 text-muted-foreground">
                I am a passionate software engineering intern with a strong background in web development. I have
                experience working with various technologies, including React, Node.js, and databases. I am always eager
                to learn and take on new challenges.
              </p>
              <p className="mt-4 text-muted-foreground">
                In my free time, I enjoy exploring new technologies, reading about the latest industry trends, and
                contributing to open- source projects. I am committed to creating user-friendly and accessible web
                applications that solve real-world problems.
              </p>
            </div>
            <div className="grid gap-4">
              <div className="rounded-lg border bg-muted p-4">
                <h3 className="text-lg font-semibold">Education</h3>
                <p className="mt-2 text-muted-foreground">
                  Bachelor of Science in Computer Science
                  <br />
                  University of Example, 2020
                </p>
              </div>
              <div className="rounded-lg border bg-muted p-4">
                <h3 className="text-lg font-semibold">Experience</h3>
                <p className="mt-2 text-muted-foreground">
                  Software Engineering Intern
                  <br />
                  Acme Inc., 2022 - Present
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="skills" className="container mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">My Skills</h2>
          <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
            <div className="rounded-lg border bg-muted p-4 text-center">
              <CodepenIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">React</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <NetworkIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Node.js</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <EclipseIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">JavaScript</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <CodepenIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">CSS</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <GitGraphIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Git</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <DatabaseIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Databases</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <TestTubesIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Testing</p>
            </div>
            <div className="rounded-lg border bg-muted p-4 text-center">
              <AccessibilityIcon className="mx-auto h-8 w-8" />
              <p className="mt-2 text-sm font-medium">Responsive Design</p>
            </div>
          </div>
        </section>
        <section id="projects" className="container mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">My Projects</h2>
          <div className="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Card>
              <CardHeader>
                <CardTitle>Project 1</CardTitle>
                <CardDescription>
                  A web application that helps users manage their tasks and to-do lists.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center gap-2">
                    <CodepenIcon className="h-6 w-6" />
                    <span>React</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <NetworkIcon className="h-6 w-6" />
                    <span>Node.js</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <DatabaseIcon className="h-6 w-6" />
                    <span>MongoDB</span>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  View Project
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Project 2</CardTitle>
                <CardDescription>A responsive e-commerce website for a local clothing retailer.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center gap-2">
                    <CodepenIcon className="h-6 w-6" />
                    <span>React</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <NetworkIcon className="h-6 w-6" />
                    <span>Node.js</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <DatabaseIcon className="h-6 w-6" />
                    <span>PostgreSQL</span>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  View Project
                </Link>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Project 3</CardTitle>
                <CardDescription>
                  A web application that allows users to track their fitness goals and progress.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center gap-2">
                    <CodepenIcon className="h-6 w-6" />
                    <span>React</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <NetworkIcon className="h-6 w-6" />
                    <span>Node.js</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <DatabaseIcon className="h-6 w-6" />
                    <span>Firebase</span>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  View Project
                </Link>
              </CardFooter>
            </Card>
          </div>
        </section>
        <section id="contact" className="container mx-auto max-w-6xl px-4 py-20 md:px-6 md:py-32">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Get in Touch</h2>
          <div className="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2">
            <div className="rounded-lg border bg-muted p-6">
              <h3 className="text-lg font-semibold">Contact Information</h3>
              <div className="mt-4 space-y-2 text-muted-foreground">
                <div className="flex items-center gap-2">
                  <MailIcon className="h-6 w-6" />
                  <span>jane.doe@example.com</span>
                </div>
                <div className="flex items-center gap-2">
                  <PhoneIcon className="h-6 w-6" />
                  <span>+1 (123) 456-7890</span>
                </div>
                <div className="flex items-center gap-2">
                  <LocateIcon className="h-6 w-6" />
                  <span>San Francisco, CA</span>
                </div>
              </div>
            </div>
            <div className="rounded-lg border bg-muted p-6">
              <h3 className="text-lg font-semibold">Send a Message</h3>
              <form className="mt-4 grid gap-4">
                <Input placeholder="Name" />
                <Input type="email" placeholder="Email" />
                <Textarea placeholder="Message" rows={4} />
                <Button type="submit" className="justify-self-end">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-8">
        <div className="container mx-auto max-w-6xl px-4 md:px-6">
          <div className="flex flex-col items-center justify-between gap-4 md:flex-row">
            <p className="text-sm text-muted-foreground">&copy; 2024 Jane Doe. All rights reserved.</p>
            <div className="flex gap-4">
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                Privacy Policy
              </Link>
              <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function AccessibilityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="16" cy="4" r="1" />
      <path d="m18 19 1-7-6 1" />
      <path d="m5 8 3-3 5.5 3-2.36 3.5" />
      <path d="M4.24 14.5a5 5 0 0 0 6.88 6" />
      <path d="M13.76 17.5a5 5 0 0 0-6.88-6" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function EclipseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a7 7 0 1 0 10 10" />
    </svg>
  )
}


function GitGraphIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="5" cy="6" r="3" />
      <path d="M5 9v6" />
      <circle cx="5" cy="18" r="3" />
      <path d="M12 3v18" />
      <circle cx="19" cy="6" r="3" />
      <path d="M16 15.7A9 9 0 0 0 19 9" />
    </svg>
  )
}


function LocateIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="2" x2="5" y1="12" y2="12" />
      <line x1="19" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="5" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <circle cx="12" cy="12" r="7" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function NetworkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function TestTubesIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 2v17.5A2.5 2.5 0 0 1 6.5 22v0A2.5 2.5 0 0 1 4 19.5V2" />
      <path d="M20 2v17.5a2.5 2.5 0 0 1-2.5 2.5v0a2.5 2.5 0 0 1-2.5-2.5V2" />
      <path d="M3 2h7" />
      <path d="M14 2h7" />
      <path d="M9 16H4" />
      <path d="M20 16h-5" />
    </svg>
  )
}
